import React, { useState } from 'react';
import type { CsvImportUserRow, PlatformUser } from '../../types/admin';
import { X, FileSpreadsheet, UploadCloud, Download, CheckCircle2, AlertCircle, ArrowRight } from 'lucide-react';

interface BulkImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImportUsers: (newUsers: PlatformUser[]) => void;
}

export const BulkImportModal: React.FC<BulkImportModalProps> = ({
  isOpen,
  onClose,
  onImportUsers,
}) => {
  if (!isOpen) return null;

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [importSummary, setImportSummary] = useState<any>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setSelectedFile(e.target.files[0]);
      setUploadError(null);
    }
  };

  const handleUploadSubmit = async () => {
    if (!selectedFile) return;
    setIsUploading(true);
    setUploadError(null);

    const formData = new FormData();
    formData.append('file', selectedFile);

    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/v1/admin/users/import', {
        method: 'POST',
        headers: token ? { Authorization: `Bearer ${token}` } : {},
        body: formData,
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.detail || 'Failed to import users file');
      }

      setImportSummary(data);
      onImportUsers([]); // Refresh parent list
    } catch (err: any) {
      setUploadError(err.message || 'An error occurred during file upload');
    } finally {
      setIsUploading(false);
    }
  };

  const handleDownloadTemplate = async () => {
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`/api/v1/admin/users/template?format=xlsx`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {}
      });
      if (!res.ok) {
        throw new Error('Failed to download template');
      }
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'cyberrange_user_import_template.xlsx';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert('Error downloading template');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-xs">
      <div className="bg-white dark:bg-slate-900 rounded-2xl max-w-2xl w-full border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-800/60">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-purple-100 dark:bg-purple-950/60 text-[#6F42C1] dark:text-purple-300">
              <FileSpreadsheet className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
                Bulk Import Users via Excel
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Batch provision multiple user accounts simultaneously</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 p-1.5 rounded-lg hover:bg-slate-200/60 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-5 max-h-[70vh] overflow-y-auto">
          {!importSummary ? (
            /* Upload Drop Area */
            <div className="space-y-4">
              {/* Guidelines Info Alert */}
              <div className="p-4 bg-blue-50/50 dark:bg-blue-950/20 border border-blue-100 dark:border-blue-900/50 rounded-2xl text-xs space-y-2">
                <span className="font-extrabold text-blue-800 dark:text-blue-300 block">📝 Excel Template Guidelines & Columns</span>
                <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
                  Your Excel sheet columns must match the standard template format. There are exactly 5 columns. Account passwords will be auto-generated by the system and emailed directly to each user.
                </p>
                <div className="grid grid-cols-2 gap-4 pt-1 font-semibold text-slate-700 dark:text-slate-300">
                  <div>
                    <span className="text-emerald-700 dark:text-emerald-400 block mb-1">Required Columns:</span>
                    <ul className="list-disc pl-4 space-y-1">
                      <li>S.No</li>
                      <li>Full Name</li>
                      <li>Email</li>
                    </ul>
                  </div>
                  <div>
                    <span className="text-slate-500 dark:text-slate-400 block mb-1">Chooseable / Presets (Optional):</span>
                    <ul className="list-disc pl-4 space-y-1">
                      <li>Department / Year (Chooseable dropdown list)</li>
                      <li>Roll Number (e.g. 22BCS001)</li>
                    </ul>
                  </div>
                </div>
              </div>

              <label className="border-2 border-dashed border-slate-300 hover:border-[#0052CC] bg-slate-50/50 hover:bg-blue-50/40 rounded-2xl p-8 text-center block cursor-pointer transition-all group">
                <input 
                  type="file" 
                  accept=".xlsx"
                  onChange={handleFileSelect}
                  className="hidden" 
                />
                <div className="w-12 h-12 rounded-2xl bg-blue-100 text-[#0052CC] flex items-center justify-center mx-auto mb-3 group-hover:scale-110 transition-transform">
                  <UploadCloud className="w-6 h-6" />
                </div>
                <h3 className="text-sm font-bold text-slate-800">
                  {selectedFile ? selectedFile.name : 'Click to Browse or Drop XLSX File Here'}
                </h3>
                <p className="text-xs text-slate-400 mt-1">
                  Supports .xlsx Excel files up to 10MB (Max 1000 users per batch)
                </p>
              </label>

              {uploadError && (
                <div className="p-3 bg-rose-50 border border-rose-200 text-rose-600 rounded-xl text-xs font-bold flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" /> {uploadError}
                </div>
              )}

              <div className="flex items-center justify-between p-3 bg-slate-100/70 rounded-xl text-xs">
                <span className="text-slate-600 font-medium">Need the standard import Excel format template?</span>
                <button
                  onClick={handleDownloadTemplate}
                  className="text-[#0052CC] font-bold hover:underline inline-flex items-center gap-1 cursor-pointer bg-transparent border-none p-0"
                >
                  <Download className="w-3.5 h-3.5" /> Download Excel Template
                </button>
              </div>
            </div>
          ) : (
            /* Upload Summary Matrix */
            <div className="space-y-4">
              <div className="flex items-center justify-between p-3 bg-emerald-50 border border-emerald-200 rounded-xl text-xs">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#28A745]" />
                  <span className="text-emerald-850 font-bold">Import Batch Upload Completed Successfully!</span>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="p-4 bg-slate-50 dark:bg-slate-850 border border-slate-150 rounded-2xl">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Total Checked</span>
                  <span className="text-xl font-black text-slate-800 dark:text-slate-100 mt-1 block">{importSummary.total_processed || 0}</span>
                </div>
                <div className="p-4 bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-150 rounded-2xl">
                  <span className="text-[10px] text-emerald-600 font-bold uppercase tracking-wider block">Created</span>
                  <span className="text-xl font-black text-[#28A745] mt-1 block">{importSummary.success_count || 0}</span>
                </div>
                <div className="p-4 bg-rose-50 dark:bg-rose-950/30 border border-rose-150 rounded-2xl">
                  <span className="text-[10px] text-rose-600 font-bold uppercase tracking-wider block">Errors</span>
                  <span className="text-xl font-black text-rose-600 mt-1 block">{importSummary.failure_count || 0}</span>
                </div>
              </div>

              {importSummary.errors && importSummary.errors.length > 0 && (
                <div className="border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden">
                  <div className="bg-slate-50 dark:bg-slate-850 px-4 py-2.5 border-b border-slate-200 dark:border-slate-850 text-xs font-bold text-slate-700 dark:text-slate-350">
                    Detailed Import Processing Failures ({importSummary.errors.length})
                  </div>
                  <div className="max-h-40 overflow-y-auto divide-y divide-slate-100 dark:divide-slate-800 text-xs">
                    {importSummary.errors.map((err: any, idx: number) => (
                      <div key={idx} className="p-3 bg-rose-50/20 text-rose-700 dark:text-rose-400 flex justify-between gap-3">
                        <span className="font-semibold">Row {err.row_index}:</span>
                        <span className="flex-1">{err.error_detail}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-100 dark:border-slate-800 flex justify-between gap-2 bg-slate-50 dark:bg-slate-800/40">
          <div>
            {importSummary && (
              <button
                onClick={() => {
                  setImportSummary(null);
                  setSelectedFile(null);
                }}
                className="px-4 py-2 bg-slate-200 hover:bg-slate-300 dark:bg-slate-700 dark:hover:bg-slate-600 text-slate-800 dark:text-slate-100 font-bold text-xs rounded-xl transition-all cursor-pointer"
              >
                Upload Another
              </button>
            )}
          </div>
          <div className="flex gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 font-bold text-xs cursor-pointer"
            >
              Cancel
            </button>
            {!importSummary && (
              <button
                onClick={handleUploadSubmit}
                disabled={!selectedFile || isUploading}
                className="px-5 py-2 bg-[#0052CC] hover:bg-[#0043A4] disabled:opacity-50 text-white font-extrabold text-xs rounded-xl shadow-xs transition-all inline-flex items-center gap-1.5 cursor-pointer"
              >
                {isUploading ? 'Uploading...' : 'Process Batch Import'}
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
