import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { AlertTriangle, ShieldAlert, TrendingUp } from "lucide-react";
import { usePrivacySoc } from "../context/PrivacySocContext.jsx";
const tabs = [{ id: "overview", label: "Overview", path: "/incident-management", icon: ShieldAlert }, { id: "breach", label: "Breach Notification", path: "/incident-management/breach", icon: AlertTriangle }, { id: "tracking", label: "Incident Tracking", path: "/incident-management/tracking", icon: TrendingUp }];
export default function IncidentModulePage() {
 const navigate=useNavigate(), location=useLocation(); const { notifications }=usePrivacySoc(); const active=tabs.find(t=>t.path===location.pathname)?.id||"overview"; const critical=notifications.filter(n=>n.type==="critical"||n.type==="warning"); const head=(k,t,p)=><section className="workflow-toolbar"><div><span className="eyebrow">{k}</span><h2>{t}</h2><p>{p}</p></div></section>;
 return <div className="module-shell consent-workspace"><div className="page-header"><div><span className="eyebrow">Incident Response</span><h1 className="page-title">Incident Management</h1><p className="page-subtitle">Separate command, notification, and investigation workflows.</p></div></div><div className="module-tabs">{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} type="button" className={`module-tab ${active===t.id?"active":""}`} onClick={()=>navigate(t.path)}><Icon size={15}/>{t.label}</button>})}</div>
 {active==="overview"&&<><>{head("Response command","Incident Overview","Understand current exposure and route responders to the correct workflow.")}</><div className="analytics-highlights"><div><span>Open alerts</span><strong>{notifications.filter(n=>!n.read).length}</strong></div><div><span>Priority review</span><strong>{critical.length}</strong></div><div><span>Response posture</span><strong>Ready</strong></div></div><section className="glass-panel workspace-card"><div className="section-heading"><h2>Response priorities</h2><p>Open a breach workflow for regulatory decisions or investigate the event trail.</p></div><div className="recommendation-list">{critical.slice(0,2).map(n=><div className="recommendation-item critical" key={n.id}><div><strong>{n.text}</strong><p>{n.time}</p></div></div>)}</div></section></>}
 {active==="breach"&&<><>{head("Regulatory workflow","Breach Notification","Assess notification thresholds and prepare communications for an identified breach.")}</><section className="glass-panel workspace-card"><div className="request-list"><article className="request-item"><div><span className="consent-status pending">Assessment required</span><h3>Payment API log exposure</h3><p>Confirm scope, affected principals, and notification deadline.</p></div><button type="button" className="premium-btn primary" onClick={()=>navigate("/incident-management/assessment")}>Start assessment</button></article><article className="request-item"><div><span className="consent-status granted">Ready</span><h3>Authority notification template</h3><p>Required facts and review owners are complete.</p></div><button type="button" className="premium-btn secondary" onClick={()=>navigate("/breach-notification")}>Review notice</button></article></div></section></>}
 {active==="tracking"&&<><>{head("Investigation workflow","Incident Tracking","Follow owners, evidence, remediation tasks, and closure decisions.")}</><section className="glass-panel workspace-card"><div className="timeline">{notifications.map(n=><div className="timeline-item" key={n.id}><i></i><div><strong>{n.text}</strong><p>{n.time} · operational signal logged</p></div><span className="sla-badge">Tracked</span></div>)}</div></section></>}
 </div>;
}
