import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Database, Fingerprint, Search, ShieldCheck } from "lucide-react";
import { usePrivacySoc } from "../context/PrivacySocContext.jsx";
import PiiMapping from "../components/PiiMapping.jsx";

const tabs = [{ id: "overview", label: "Overview", path: "/privacy-management", icon: ShieldCheck }, { id: "discovery", label: "Data Discovery", path: "/privacy-management/discovery", icon: Search }, { id: "classification", label: "Data Classification", path: "/privacy-management/classification", icon: Fingerprint }, { id: "retention", label: "Data Retention", path: "/privacy-management/retention", icon: Database }];
export default function PrivacyModulePage() {
  const navigate = useNavigate(); const location = useLocation(); const { activeApiKey, piiCount, piiFields } = usePrivacySoc(); const active = tabs.find((tab) => tab.path === location.pathname)?.id || "overview";
  const high = piiFields.filter((x) => String(x.risk || x.sensitivity).toLowerCase() === "high").length;
  const header = (kicker, title, text) => <section className="workflow-toolbar"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{text}</p></div></section>;
  return <div className="module-shell consent-workspace"><div className="page-header"><div><span className="eyebrow">Privacy Operations</span><h1 className="page-title">Privacy Management</h1><p className="page-subtitle">Separate workspaces for privacy posture, discovery, classification, and retention.</p></div></div><div className="module-tabs">{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} className={`module-tab ${active === tab.id ? "active" : ""}`} onClick={() => navigate(tab.path)}><Icon size={15}/>{tab.label}</button>; })}</div>
    {active === "overview" && <><>{header("Privacy posture", "Privacy Overview", "Assess the operating posture and the work that needs attention.")}</><div className="analytics-highlights"><div><span>PII fields</span><strong>{piiFields.length}</strong></div><div><span>High sensitivity</span><strong>{high}</strong></div><div><span>Connected sources</span><strong>{activeApiKey ? 1 : 0}</strong></div></div><section className="glass-panel workspace-card"><div className="section-heading"><h2>Priority actions</h2><p>Start a specific privacy workflow from the module navigation.</p></div><div className="recommendation-list"><div className="recommendation-item warning"><div><strong>Classify high-risk fields</strong><p>{high} fields require a sensitivity and control review.</p></div></div><div className="recommendation-item healthy"><div><strong>Review retention schedule</strong><p>Validate deletion obligations against the discovered inventory.</p></div></div></div></section></>}
    {active === "discovery" && <><>{header("Inventory workflow", "Data Discovery", "Inspect detected personal data, sources, and field-level evidence.")}</>{activeApiKey ? <PiiMapping activeApiKey={activeApiKey}/> : <section className="glass-panel workspace-card"><p className="module-panel-copy">Connect a source to start data discovery.</p></section>}</>}
    {active === "classification" && <><>{header("Control assignment", "Data Classification", "Assign and validate sensitivity classifications for discovered fields.")}</><section className="glass-panel workspace-card"><div className="table-wrap"><table className="premium-table"><thead><tr><th>Field</th><th>Data type</th><th>Risk</th><th>Recommended control</th></tr></thead><tbody>{piiFields.map((field, i) => <tr key={`${field.column}-${i}`}><td>{field.column}</td><td>{field.pii_type || "Personal data"}</td><td><span className={`consent-status ${String(field.risk || "low").toLowerCase() === "high" ? "revoked" : "pending"}`}>{field.risk || "Low"}</span></td><td>{String(field.risk).toLowerCase() === "high" ? "Encryption + restricted access" : "Access review"}</td></tr>)}{!piiFields.length && <tr><td colSpan="4" className="empty-state">No classification inventory is available.</td></tr>}</tbody></table></div></section></>}
    {active === "retention" && <><>{header("Lifecycle control", "Data Retention", "Manage retention schedules and upcoming deletion obligations.")}</><section className="glass-panel workspace-card"><div className="timeline"><div className="timeline-item"><i></i><div><strong>Marketing contact data</strong><p>Retention ends in 14 days · deletion workflow not started</p></div><span className="sla-badge risk">Review due</span></div><div className="timeline-item"><i></i><div><strong>Research responses</strong><p>Retention review completed · next review in 90 days</p></div><span className="sla-badge">On track</span></div></div></section></>}
  </div>;
}
