import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Download, FileText, ShieldCheck } from "lucide-react";
import { usePrivacySoc } from "../context/PrivacySocContext.jsx";
import Reports from "./Reports.jsx";
const tabs=[{id:"overview",label:"Overview",path:"/reports",icon:ShieldCheck},{id:"compiler",label:"Compiler",path:"/reports/compiler",icon:FileText},{id:"audit",label:"Audit Logs",path:"/reports/audit-logs",icon:ShieldCheck},{id:"export",label:"Export",path:"/reports/export",icon:Download}];
export default function ReportsModulePage(){const navigate=useNavigate(),location=useLocation();const{notifications,consents,addNotification}=usePrivacySoc();const active=tabs.find(t=>t.path===location.pathname)?.id||"overview";const[compiled,setCompiled]=useState(false);const[exporting,setExporting]=useState("");const head=(k,t,p)=><section className="workflow-toolbar"><div><span className="eyebrow">{k}</span><h2>{t}</h2><p>{p}</p></div></section>;const download=(filename,content,type="text/plain")=>{const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([content],{type}));link.download=filename;link.click();URL.revokeObjectURL(link.href);};const exportConsent=()=>{setExporting("csv");window.setTimeout(()=>{download("consent-evidence.csv",["User ID,Name,Email,Purpose,Status,Timestamp",...consents.map(c=>[c.user_id,c.name,c.email,c.purpose,c.consent_status,c.timestamp].map(v=>`\"${String(v??"").replaceAll("\"","\"\"")}\"`).join(","))].join("\n"),"text/csv");setExporting("");addNotification("Consent evidence package exported.","success");},250)};const exportSummary=()=>{setExporting("pdf");window.setTimeout(()=>{download("compliance-summary.txt",`Compliance summary\n\nConsent records: ${consents.length}\nOperational events: ${notifications.length}\nGenerated: ${new Date().toLocaleString()}`);setExporting("");addNotification("Compliance summary prepared for download.","success");},250)};return <div className="module-shell consent-workspace"><div className="page-header"><div><span className="eyebrow">Reporting & Evidence</span><h1 className="page-title">Reports</h1><p className="page-subtitle">Distinct report review, compilation, audit, and export workflows.</p></div></div><div className="module-tabs">{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} type="button" className={`module-tab ${active===t.id?"active":""}`} onClick={()=>navigate(t.path)}><Icon size={15}/>{t.label}</button>})}</div>
{active==="overview"&&<><>{head("Report library","Report Overview","Browse decision-ready privacy and compliance summaries.")}</><Reports/></>}
{active==="compiler"&&<><>{head("Authoring workflow","Report Compiler","Create a stakeholder-ready package from a defined reporting scope.")}</><section className="glass-panel workspace-card"><div className="consent-filters"><select><option>Executive readiness report</option><option>Consent operations report</option><option>DPDP evidence pack</option></select><select><option>Current month</option><option>Previous quarter</option></select><button className="premium-btn primary" onClick={()=>setCompiled(true)}>Compile report</button></div>{compiled&&<div className="recommendation-item healthy"><div><strong>Report compiled</strong><p>The draft is ready for review and export.</p></div></div>}</section></>}
{active==="audit"&&<><>{head("Evidence review","Audit Logs","Inspect the immutable operational trail supporting compliance reviews.")}</><section className="glass-panel workspace-card"><div className="table-wrap"><table className="premium-table"><thead><tr><th>Event</th><th>Time</th><th>Category</th></tr></thead><tbody>{notifications.map(n=><tr key={n.id}><td>{n.text}</td><td>{n.time}</td><td>System activity</td></tr>)}</tbody></table></div></section></>}
{active==="export"&&<><>{head("Evidence delivery","Export Packages","Prepare controlled exports for auditors, leadership, or regulators.")}</><section className="glass-panel workspace-card"><div className="request-list"><article className="request-item"><div><h3>Consent evidence package</h3><p>{consents.length} registry records, approval decisions, and revocation evidence.</p></div><button type="button" className="premium-btn primary" onClick={exportConsent} disabled={exporting!==""||consents.length===0}>{exporting==="csv"?"Exporting…":"Export CSV"}</button></article><article className="request-item"><div><h3>Compliance summary</h3><p>Executive-ready summary of current records and operational activity.</p></div><button type="button" className="premium-btn secondary" onClick={exportSummary} disabled={exporting!==""}>{exporting==="pdf"?"Preparing…":"Prepare summary"}</button></article></div></section></>}
</div>}
