import React, { useEffect, useState } from "react";
import { Download, Search, ShieldCheck, X } from "lucide-react";
import { getSharingEvidenceUrl, getSharingRecord, getSharingRecords } from "../services/anonymizationApi.js";

const formatDate = (value) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const shortHash = (hash) => `${hash.slice(0, 12)}…${hash.slice(-8)}`;

export default function ThirdPartySharingLogPage() {
  const [query, setQuery] = useState(""); const [records, setRecords] = useState([]); const [selected, setSelected] = useState(null); const [error, setError] = useState("");
  useEffect(() => { const timer = setTimeout(() => getSharingRecords(query).then(setRecords).catch((err) => setError(err.message)), 150); return () => clearTimeout(timer); }, [query]);
  const viewRecord = async (shareId) => { try { setSelected(await getSharingRecord(shareId)); } catch (err) { setError(err.message); } };
  return <div className="module-shell sharing-workspace"><div className="page-header"><div><span className="eyebrow">Processor accountability</span><h1 className="page-title">Third-Party Sharing Log</h1><p className="page-subtitle">Immutable evidence for personal-data disclosures to external processors.</p></div></div><section className="glass-panel workspace-card"><div className="sharing-toolbar"><div className="section-heading"><h2>Sharing audit records</h2><p>Every disclosure is recorded with a SHA-256 payload integrity value.</p></div><label className="search-field"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, processor, purpose, or hash" /></label></div>{error && <p className="module-error">{error}</p>}<div className="table-wrap"><table className="premium-table"><thead><tr><th>Share ID</th><th>Processor</th><th>Purpose</th><th>Timestamp</th><th>Hash</th><th>Status</th></tr></thead><tbody>{records.map((item) => <tr className="selectable-row" onClick={() => viewRecord(item.shareId)} key={item.shareId}><td><strong>{item.shareId}</strong></td><td>{item.processorName}</td><td>{item.purpose}</td><td>{formatDate(item.timestamp)}</td><td><code className="hash-value">{shortHash(item.payloadHash)}</code></td><td><span className="anonymization-status verified">{item.verificationStatus}</span></td></tr>)}{!records.length && <tr><td colSpan="6" className="empty-state">No sharing audit records match this search.</td></tr>}</tbody></table></div></section>{selected && <section className="glass-panel detail-drawer"><div className="panel-header"><div><p className="panel-kicker">Audit evidence</p><h3>{selected.shareId}</h3></div><button className="icon-button" onClick={() => setSelected(null)}><X size={18}/></button></div><div className="detail-grid sharing-detail-grid"><span>Processor<strong>{selected.processorName}</strong></span><span>Purpose<strong>{selected.purpose}</strong></span><span>Timestamp<strong>{formatDate(selected.timestamp)}</strong></span><span>Shared fields<strong>{selected.sharedFields.join(", ")}</strong></span><span>Consent reference<strong>{selected.consentReference}</strong></span><span>Integrity verification<strong><ShieldCheck size={15}/> {selected.integrityVerification.status}</strong></span></div><div className="hash-evidence"><span>Generated SHA-256 hash</span><code>{selected.payloadHash}</code></div><a className="premium-btn secondary" href={getSharingEvidenceUrl(selected.shareId)}><Download size={16}/> Download audit evidence</a></section>}</div>;
}
